#! /bin/bash

DEPLOYMENT_PORT=$1
CONTAINER_NAME=$2
VOLUME_PATH_HOST=$3
VOLUME_PATH_CONTAINER=$4

DEFAULT_IMAGE=alpine:3.19.1

docker run -dt -p $DEPLOYMENT_PORT:3030 --name $CONTAINER_NAME -v $VOLUME_PATH_HOST:$VOLUME_PATH_CONTAINER $DEFAULT_IMAGE
